version: "3.8"

services: 
    client:
        stdin_open: true
        container_name: vouchers_client
        build:
          context: ./client
          dockerfile: Dockerfile
        volumes:
          - './client/:/app'
          - '/app/node_modules'
        ports:
          - 3030:3030
        environment:
          - CHOKIDAR_USEPOLLING=true # For hot-reloading

    server:
        container_name: vouchers_server
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - 8080:8080
            