sudo: required
addons:
  chrome: stable
  hostname: localhost
language: groovy
jdk:
  - openjdk8
node_js:
  - "12"
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - sudo apt-get install chromium-browser
  - curl -s http://get.sdkman.io | bash
  - echo sdkman_auto_answer=true > ~/.sdkman/etc/config
  - source "/home/travis/.sdkman/bin/sdkman-init.sh"
  - sdk install grails 4.0.5
  - nvm install 12.14.1 && nvm use 12.14.1
before_script:
  - cd server && grails test-app
	- cd client && node --version && npm install pm2 -g && npm install
  - ./gradlew server:bootRun &
  - sleep 20
  - cd client && pm2 start npm -- start
  - sleep 20
script: "cd Vouchers && make run-test"