sudo: false
addons:
  chrome: stable
language: groovy
jdk:
  - openjdk8
node_js:
  - "12"
before_install:
  - curl -s http://get.sdkman.io | bash
  - echo sdkman_auto_answer=true > ~/.sdkman/etc/config
  - source "/home/travis/.sdkman/bin/sdkman-init.sh"
  - sdk install grails 4.0.5
  - nvm install 12.14.1 && nvm use 12.14.1
  - sudo apt-get install chromium-browser
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script: "cd Vouchers && make run-test"